### ISSUE TITLE
Можно тут задавать вопросы?

### ISSUE THREAD

**Issue by MK5555** [irlndts/coursera-go-homework#1]
Хотел бы узнать про несколько моментов в коде, если возможно.

**Comment by irlndts** [comment]
Привет, я этим занимался пару лет назад, уже не особо помню что там было.
Но попробовать можно, конечно.

**Comment by MK5555** [comment]
Второе задание. Зачем делать присваивание in = out после запуска воркера и зачем выделять память под канал out, если она уже выделена (код функции ниже)? 
`
func ExecutePipeline(jobs ...job) {
	in := make(chan interface{}, 100)
	out := make(chan interface{}, 100)

	wg := &sync.WaitGroup{}
	for _, job := range jobs {
		wg.Add(1)
		go worker(wg, job, in, out)
		in = out
		out = make(chan interface{}, 100)
	}

	wg.Wait()
}`

**Comment by irlndts** [comment]
я тут вижу, что in = out делается для того, чтоб в следующей итерации на вход go worker в in попадало то, что пришло в out. 
а make делается для того, чтоб инициализировать новый out, который был закрыт внутри воркера.

Сейчас это выглядит странно для меня и вряд ли бы я стал так делать, поэтому не рекомендую повторять)

**Comment by MK5555** [comment]
Спасибо
